### ISSUE TITLE
BasicModelInterface.jl

### ISSUE THREAD

**Issue by visr** [csdms/bmi-julia#1]
Hi! I know this repo is only an hour old and still empty, but I was excited to see it pop up on my feed, together with https://github.com/csdms/bmi-example-julia.

A few years ago I made https://github.com/Deltares/BasicModelInterface.jl, and at Deltares we've been using it, for instance in https://github.com/Deltares/Wflow.jl and https://github.com/Deltares/ModflowInterface.jl.

I haven't really been seeking CSDMS adopting actively, besides casually mentioning it https://github.com/csdms/bmi-python/issues/6, so I'm not sure you are aware of this registered Julia package. As I mention in the package's readme, I'm open for collaboration on this.

**Comment by mdpiper** [comment]
Hi @visr! There are a few competing Julia BMI specifications (yours included). We plan to discuss how to meld them into one at the next BMI Council meeting.

**Comment by visr** [comment]
Ok I see, great. I'm not aware of the others yet. Let me know if you want me to clarify any design choices.

**Comment by visr** [comment]
I'll close this in favour of https://github.com/csdms/bmi/issues/108.
